package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorAllPropertiesEquals(Autor expected, Autor actual) {
        assertAutorAutoGeneratedPropertiesEquals(expected, actual);
        assertAutorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorAllUpdatablePropertiesEquals(Autor expected, Autor actual) {
        assertAutorUpdatableFieldsEquals(expected, actual);
        assertAutorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorAutoGeneratedPropertiesEquals(Autor expected, Autor actual) {
        assertThat(actual)
            .as("Verify Autor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorUpdatableFieldsEquals(Autor expected, Autor actual) {
        assertThat(actual)
            .as("Verify Autor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorUpdatableRelationshipsEquals(Autor expected, Autor actual) {
        // empty method
    }
}
