package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ComentarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComentarioAllPropertiesEquals(Comentario expected, Comentario actual) {
        assertComentarioAutoGeneratedPropertiesEquals(expected, actual);
        assertComentarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComentarioAllUpdatablePropertiesEquals(Comentario expected, Comentario actual) {
        assertComentarioUpdatableFieldsEquals(expected, actual);
        assertComentarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComentarioAutoGeneratedPropertiesEquals(Comentario expected, Comentario actual) {
        assertThat(actual)
            .as("Verify Comentario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComentarioUpdatableFieldsEquals(Comentario expected, Comentario actual) {
        assertThat(actual)
            .as("Verify Comentario relevant properties")
            .satisfies(a -> assertThat(a.getTexto()).as("check texto").isEqualTo(expected.getTexto()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComentarioUpdatableRelationshipsEquals(Comentario expected, Comentario actual) {
        assertThat(actual)
            .as("Verify Comentario relationships")
            .satisfies(a -> assertThat(a.getPublicacion()).as("check publicacion").isEqualTo(expected.getPublicacion()));
    }
}
