package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtiquetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAllPropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertEtiquetaAutoGeneratedPropertiesEquals(expected, actual);
        assertEtiquetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAllUpdatablePropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertEtiquetaUpdatableFieldsEquals(expected, actual);
        assertEtiquetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaAutoGeneratedPropertiesEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(actual)
            .as("Verify Etiqueta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaUpdatableFieldsEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(actual)
            .as("Verify Etiqueta relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaUpdatableRelationshipsEquals(Etiqueta expected, Etiqueta actual) {
        assertThat(actual)
            .as("Verify Etiqueta relationships")
            .satisfies(a -> assertThat(a.getPublicacions()).as("check publicacions").isEqualTo(expected.getPublicacions()));
    }
}
